name: Docker Image Builder

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Perform Checkout

      - name: Docker Build and Push
        uses: mr-smithers-excellent/docker-build-push@v5.6
        with:
          image: blacklist-redis
          tags: latest
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
